### ISSUE TITLE
Opsworks - when you already are using a custom git repo

### ISSUE THREAD

**Issue by atlesp** [logentries/le_chef#14]
We want to add this to our OpsWorks stacks, but we are already using a custom git cookbook repo.
What is best practice then? Create a custom stack that the instances also needs to be member of or adding your receipes to our own repo?

**Comment by ptdixon** [comment]
@atlesp Sorry, I don't really understand your question...?

**Comment by joeheung** [comment]
@atlesp I don't have much experience with opsworks, do you use berksfile or librarian-chef to manage the cookbooks? If so you could add the following:

```
cookbook 'logentries', git: => 'https://github.com/logentries/le_chef.git'
```

**Comment by atlesp** [comment]
No, we do not do that. Figured out that the easiest was to merge this cookbok into ours.
Bur when running it I get a error that the logentries package can not be found:
 
```Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '2'
---- Begin output of apt-key adv --keyserver pgp.mit.edu --recv C43C79AD ----
STDOUT: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.0d0JFASKeZ --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver pgp.mit.edu --recv C43C79AD
gpgkeys: key C43C79AD can't be retrieved
STDERR: gpg: requesting key C43C79AD from hkp server pgp.mit.edu
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
---- End output of apt-key adv --keyserver pgp.mit.edu --recv C43C79AD ----
Ran apt-key adv --keyserver pgp.mit.edu --recv C43C79AD returned 2
 ```

**Comment by atlesp** [comment]
I had to change the keyserver  to   'hkp://pgp.mit.edu:80'. This since the default port is blocked in FW. Should maybe be the default value?

Thanks for a great product.
