### ISSUE TITLE
Renaming cookbook breaks existing deployments

### ISSUE THREAD

**Issue by daniel-nelson** [logentries/le_chef#21]
A recent commit changed the name of this cookbook from "le_chef" to "logentries_agent". This breaks existing deployments (we just tried to add a new instance to production, and this change caused it to fail). It isn't hard to fix, but it doesn't seem like a good policy for an official, public repository to make breaking changes.

**Comment by joeheung** [comment]
Hey Daniel, sorry about that, I knew it could potentially cause issues which is why I bumped the version number. The main reason for the change is that we pushed it into supermarket.chef.io and le_chef was too verbose, logentries_agent makes more sense and searchable.

**Comment by daniel-nelson** [comment]
Nice. Thanks @joeheung. Bound to the version now.
