### ISSUE TITLE
github/supermarket mismatch and version tracking

### ISSUE THREAD

**Issue by acoulton** [logentries/le_chef#26]
Hi,

It seems like the [releases on supermarket](https://supermarket.chef.io/cookbooks/logentries_agent/versions/0.2.1) have diverged from this repository?

The 0.2.0 release doesn't seem to include aeef648 but does include more recent commits eg the change to name and version number. The 0.2.1 release contains files that are not present at all in the repository.

It's also trickier than it could be to double-check for changes between versions because there are no git tags for the releases. Generally when I update a third-party cookbook I like to review the changelog and if that's not present/not clear I review the github compare between the two versions.

Also, it looks like you've not configured a link back to the github repo from the supermarket package page, which makes it a teeny bit harder to link between.

**Comment by joeheung** [comment]
Thanks for raising this Andrew.

I'll look into this issue this morning. I think once it's linked to github most issues will be sorted.

**Comment by joeheung** [comment]
Hi @acoulton,
I have added links to supermarket.chef.io and updated our deploy process for pushing the logentries_agent cookbook. I'm just wondering, what are the conflicting files that are present in one and not in the other?
Thanks,
Joe

**Comment by acoulton** [comment]
Hi @joeheung thanks - when I compare the current master branch to the 0.2.2 release downloaded from supermarket I see:

```
$ diff -r le_chef-master/ logentries_agent/
Only in logentries_agent/: Berksfile
Only in logentries_agent/: Berksfile.lock
Only in logentries_agent/: .gitignore
Only in logentries_agent/: .kitchen.yml
Only in logentries_agent/: le_chef.iml
Only in logentries_agent/: metadata.json
```

I think the metadata.json is added by supermarket, but the other files are part of the cookbook source (and not present in the git repo)?

**Comment by joeheung** [comment]
Looks like I missed the chefignore file, Ill add it and update the repo. Thanks!

**Comment by acoulton** [comment]
@joeheung thanks for this - it looks though like the releases still aren't being tagged in git, that's always helpful but especially since there's no changelog?

**Comment by joeheung** [comment]
Thanks @acoulton , I've tagged the latest version and will add it to our deploy process, can you verify?

**Comment by acoulton** [comment]
Great, thanks - that looks good.
