### ISSUE TITLE
Latest Commit Breaks Opsworks

### ISSUE THREAD

**Issue by jamiegwatkin** [logentries/le_chef#28]
The following commit - https://github.com/logentries/le_chef/commit/b93d9db6f9ca5805a304c3657581e374e7d7af72 breaks deployments when using Amazon Opsworks.

Amazon Opsworks uses Chef version 11 and not 12, source_url and issues_url was introduced in Chef 12 - https://github.com/chef/chef/blob/9760d40e2f924e8fdd5b42760c4fb775572fb777/RELEASE_NOTES.md#new-cookbook-metadata-attributes-for-supermarket.

I'm not expecting you to do anything about this, I just wanted to point it out incase other users have the same problem.

A temporary fix that we're currently using is to specify the commit hash inside a Berksfile to a commit before the breaking change -

```
cookbook 'logentries_agent', github: 'logentries/le_chef', ref: "4946b24e61a46e61102ef7f449a4fcfa9b00f5b2"

**Comment by joeheung** [comment]
Hi Jamie,

To be honest it was added for issue #26, if it's a breaking change I think we can revert. I'm not sure if Opsworks plans on updating to Chef 12 or not but am happy to rollback. What do you think?

Thanks,
Joe

**Comment by jamiegwatkin** [comment]
Joe,

I can confirm that this is a breaking change.

Amazon Opsworks gives us no control over the Chef version, I can't imagine we're the only guys using LogEntries and Opsworks.

I was trying to think of a way to keep the committed change but also support Chef 11 and I couldn't come up with a solution.

I tried finding a roadmap to see if Amazon is planning on supporting Chef 12 anytime soon but I wasn't able to find one.

Cheers,

Jamie

**Comment by deuxshaish** [comment]
Not sure if you're referring to something else, but Opsworks does give you
control over Chef version, except that version 12 is not yet supported. You
can change that from the Stack setting as seen here:

[image: Inline image 1]

Tarek
http://www.hashdoc.com/tarek

**Comment by jamiegwatkin** [comment]
@deuxshaish I never knew, thank's for the heads up.

**Comment by alexlouden** [comment]
This commit broke deployments for me too, with the following message:

```Fetching 'logentries_agent' from git://github.com/logentries/le_chef.git (at master)
The following error occurred while reading the cookbook `logentries_agent':
Ridley::Errors::FromFileParserError: Could not parse `/tmp/d20150410-14519-5cmcxf/metadata.rb': undefined method `source_url' for #<Ridley::Chef::Cookbook::Metadata:0x0000000134d608>
```

```$ chef-solo -v
Chef: 11.18.0.rc.1
```

**Comment by joeheung** [comment]
@jamiegwatkin & @alexlouden I've have a PR #29 which looks to fix the issue you're having, would you mind taking a look? I don't use AWS Opsworks so can't test there.
~ Joe

**Comment by joeheung** [comment]
#29 merged which should resolve the above issue.
